# Default debian config. Please, take a look at conntrackd.conf(5)

General {
	HashSize 8192
	HashLimit 65535

	Syslog on

	LockFile /var/lock/conntrackd.lock

	UNIX {
		Path /var/run/conntrackd.sock
		Backlog 20
	}

	SocketBufferSize 262142
	SocketBufferSizeMaxGrown 655355

	# default debian service unit file is of Type=notify
	#Systemd on
}

#Stats {
#	LogFile on
#}



Sync {
    Mode FTFW {
        DisableExternalCache On
    }
    Multicast {
        IPv4_address 225.0.0.50
        Group 3780
        IPv4_interface 10.0.0.53
        Interface eth2            # interface de sync a eth2
        SndSocketBuffer 8388608
        RcvSocketBuffer 8388608
        Checksum on
    }
}
