# Interface para a Internet
vrrp_instance VI_INTERNET {
    state BACKUP
    interface eth0
    virtual_router_id 107
    priority 100            # FW8 é Backup (FW7 é 150)
    advert_int 1

    unicast_src_ip 100.0.0.8
    unicast_peer {
        100.0.0.7
    }

    virtual_ipaddress {
        100.0.0.254/24 dev eth0
    }
}





