vrrp_instance VI_DATACENTER {
    state MASTER
    interface eth0
    virtual_router_id 55
    priority 150
    advert_int 1
    unicast_src_ip 10.100.0.5
    unicast_peer {
        10.100.0.6
    }
    virtual_ipaddress {
        10.100.0.254/16 dev eth0
    }
}


