# Interface para a Internet
vrrp_instance VI_INTERNET {
    state MASTER
    interface eth0          # Interface ligada ao switch da Internet
    virtual_router_id 107
    priority 150            # FW7 é Master, FW8 será 100
    advert_int 1

    unicast_src_ip 100.0.0.7 # IP físico da FW7 na eth0
    unicast_peer {
        100.0.0.8            # IP físico da FW8 na eth0
    }

    virtual_ipaddress {
        100.0.0.254/24 dev eth0
    }
}

