vrrp_instance VI_VLAN1 {
    state MASTER
    interface eth0.1
    virtual_router_id 11
    priority 150
    advert_int 1

    unicast_src_ip 10.0.0.1
    unicast_peer {
        10.0.0.2
    }

    virtual_ipaddress {
        10.1.0.1/24 dev eth0.1
    }
}

vrrp_instance VI_VLAN10 {
    state MASTER
    interface eth0.10
    virtual_router_id 12
    priority 150
    advert_int 1

    unicast_src_ip 10.0.0.1
    unicast_peer {
        10.0.0.2
    }

    virtual_ipaddress {
        10.10.0.1/24 dev eth0.10
    }
}

vrrp_instance VI_VLAN20 {
    state MASTER
    interface eth0.20
    virtual_router_id 13
    priority 150
    advert_int 1

    unicast_src_ip 10.0.0.1
    unicast_peer {
        10.0.0.2
    }

    virtual_ipaddress {
        10.20.0.1/24 dev eth0.20
    }
}

