#!/bin/sh

ip addr add 10.10.0.100/24 dev eth0
#ip route add default via 10.10.0.3 metric 10
#ip route add default via 10.10.0.4 metric 20
ip route add default via 10.10.0.1


# Samba
socat -d2 TCP-LISTEN:445,reuseaddr,fork SYSTEM:'while read msg; do echo "VLAN10 Samba reply: $msg"; done' &
socat -d2 TCP-LISTEN:139,reuseaddr,fork SYSTEM:'while read msg; do echo "VLAN10 Samba reply: $msg"; done' &

# SSH
socat -d2 TCP-LISTEN:22,reuseaddr,fork SYSTEM:'while read msg; do echo "VLAN10 SSH reply: $msg"; done' &

