#!/bin/sh

ip addr add 10.1.0.100/24 dev eth0
#ip route add default via 10.1.0.3 metric 10
#ip route add default via 10.1.0.4 metric 20
ip route add default via 10.1.0.1

# SSH

socat -d2 TCP-LISTEN:22,reuseaddr,fork SYSTEM:'while read msg; do echo "VLAN1 SSH reply: $msg"; done' &

